apiVersion: v1
kind: Service
metadata:
  name: maplibre-gl-openindoor
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: maplibre-gl-openindoor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: maplibre-gl-openindoor
  name: maplibre-gl-openindoor
spec:
  replicas: 1
  selector:
    matchLabels:
      run: maplibre-gl-openindoor
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: maplibre-gl-openindoor
    spec:
      containers:
      - env:
        - name: APP_DOMAIN_NAME
          valueFrom:
            configMapKeyRef:
              name: openindoor-cm
              key: appDomainName
        image: openindoor/maplibre-gl-openindoor:0.0.0
        name: maplibre-gl-openindoor
        ports:
        - containerPort: 80
