name: Release docker image and push npm to registry

on:
  push:
    tags:
    - '*'

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  IMAGE: openindoor/mapbox-gl-openindoor
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: cluster-1
  GKE_ZONE: europe-north1-a

jobs:
  setup-release-publish:
    name: Build and release docker image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ github.token }}

    # Login to Docker Hub using helper
    -  name: Login to Docker Hub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN    }}

    # Build the Docker image
    - name: Build
      run: |-
        #Pull the image to save the build time
        docker build \
          --tag "$IMAGE":"${GITHUB_REF##*/}" \
          --build-arg NPM_TOKEN=${{ secrets.NPM_TOKEN }} \
          .

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "$IMAGE":"${GITHUB_REF##*/}"

  release-npm:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - uses: fregante/setup-git-user@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        always-auth: true
        #registry-url: 'https://registry.npmjs.org'
    - run: yarn install
    - run: yarn build
    - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
    - run: yarn publish --new-version "${GITHUB_REF##*/}"
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: dist/mapbox-gl-openindoor.umd.min.js
        gzip: false
